name: CI Global (Back & Front)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: gestion_marches_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgresql
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          # On retire 'cache: maven' d'ici pour éviter qu'il cherche le pom.xml à la racine

      - name: Compiler et tester le Back-end
        run: mvn -B verify
        working-directory: ./backend

      - name: Sauvegarder le JAR (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: backend/target/*.jar

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json # Vérifiez si vous avez package-lock.json ou yarn.lock dans frontend/

      - name: Installer les dependances Front-end
        run: npm install
        working-directory: ./frontend

      - name: Builder le Front-end
        run: npm run build
        working-directory: ./frontend